### ISSUE TITLE
Sidecar dylib binary errors: PyInstaller --onedir does not play nicely with Tauri sidecar pattern

### ISSUE THREAD

**Issue by gjreda** [refstudio/refstudio#56]
The sidecar binary will inconsistently throw the following error:
```
usage: main [-h] [--debug] {ingest,ai} ...
main: error: argument command: invalid choice: 'from multiprocessing.resource_tracker import main;main(14)' (choose from 'ingest', 'ai')
```
Sometimes this error will not be thrown. Other times it will be thrown and not return any results. Other times it will return the proper results _and then_ throw this error.

It seems related to spawning multiple processes deeper within the binary, likely coming from one of the `sentence-transformers` dependencies. We do not currently do any explicit multiprocessing.

This seems like a relevant issue from the pyinstaller github:
- https://github.com/pyinstaller/pyinstaller/issues/4865

**Comment by gjreda** [comment]
For PR #29, I toyed with removing `--onefile` and it seemed to result in different errors. Some examples:

```
[Error] Unhandled Promise Rejection: Error: Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 110, in <module>
  File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 97, i...

	(anonymous function) (filesystem.tsx:50)

[Error] Unhandled Promise Rejection: Error: Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 16, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File ...

	(anonymous function) (filesystem.tsx:50)
```

This is coming from the JS console, so I don't think the Unhandled Promise is actually related ... the error is happening in the Python binary and propagating up.

I'll plan to investigate this further in conjunction with https://github.com/refstudio/refstudio/issues/48

**Comment by gjreda** [comment]
Investigating this further ...

Running PyInstaller in `--onedir` mode (as opposed to `--onefile`):
```bash
$ poetry run pyinstaller --noconfirm --hidden-import torch --collect-data torch --recursive-copy-metadata torch --hidden-import pyarrow --collect-data pyarrow --recursive-copy-metadata pyarrow --collect-binaries pyarrow --collect-submodules pyarrow --recursive-copy-metadata tqdm --recursive-copy-metadata sentence-transformers --distpath src-tauri/bin/python src-python/main.py
```

This produces a binary that works on its own:
```bash
$ ./src-tauri/bin/python/main-aarch64-apple-darwin/main ai --text "Hello world"
{"num_words": 2}
```

But if it is called from within the Tauri sidecar, the below error is thrown by the sidecar, ultimately bubbling up to the tauri app:
```
[Log] Traceback (most recent call last): (filesystem.tsx, line 53)
  File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 110, in <module>
  File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 97, in _pyi_rth_multiprocessing
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "multiprocessing/popen_forkserver.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "multiprocessing/forkserver.py", line 11, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "multiprocessing/connection.py", line 18, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "tempfile.py", line 45, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "random.py", line 58, in <module>
    
ImportError: dlopen(/Users/greg/Dropbox/refstudio/src-tauri/target/debug/_random.cpython-310-darwin.so, 0x0002): Library not loaded: @loader_path/../../libomp.dylib
  Referenced from: <D4B9F8DF-05EF-32A0-AD24-215B4E3156AE> /Users/greg/Dropbox/refstudio/src-tauri/target/debug/_random.cpython-310-darwin.so
  Reason: tried: '/Users/greg/Dropbox/refstudio/src-tauri/target/debug/../../libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)
[8421] Failed to execute script 'pyi_rth_multiprocessing' due to unhandled exception!
```

It seems that Tauri is looking in the wrong paths for the dylib files.

**Comment by hammer** [comment]
@gjreda shared library path configuration sounds like a great question for the Tauri discord!

**Comment by hammer** [comment]
If we get stuck here another path is to host a Python web service and have the sidecar (or just Rust) be a thin client that calls to the sever. We will need this architecture when we run as a web app eventually so if we get stuck on Python build (a classic tar pit!) that is one escape hatch for us.
